COLS_OBJS_ESPECIFICOS = {
    "1a": "obj_1a",
    "1b": "obj_1b",
    "2a": "obj_2a",
    "2b": "obj_2b",
    "2c": "obj_2c",
    "3a": "obj_3a",
    "3b": "obj_3b",
    "4a": "obj_4a",
    "4b": "obj_4b",
    "4c": "obj_4c",
    "4d": "obj_4d",
    "5a": "obj_5a",
    "5b": "obj_5b",
    "6a": "obj_6a",
    "6b": "obj_6b",
    "6c": "obj_6c",
    "6d": "obj_6d",
    "6e": "obj_6e",
    "6f": "obj_6f",
}
